#! ../waf
# encoding: utf-8

import sys

def options(opt):
    opt.load('compiler_cxx')

def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.env.append_value('LINKFLAGS',
                         ['-lGLESv2', '-lEGL', '-lX11', '-lm', '-lpthread'])

def build(bld):
    src = bld.path.ant_glob('*.cc')
    bld.program(features='cxx', source=src, target='zutty',
                use=['FT'], install_path=None)
