#! ../waf
# encoding: utf-8

def options(opt):
    opt.load('compiler_cxx')

def configure(cfg):
    cfg.load('compiler_cxx')

def build(bld):
    src = bld.path.ant_glob('*.cc')
    bld.program(features='cxx', source=src, target='zutty',
                use=['EGL', 'FT', 'GLES', 'THREAD', 'XMU'])
